// dswok-quartz edge Worker
//
// Handles legacy Obsidian Publish URL redirects (e.g.
// /General%20ML/Decision%20Tree  ->  /General-ML/Decision-Tree),
// then falls through to the static Quartz output via the ASSETS binding.
//
// The redirect map is generated by ../generate-redirects.mjs at build time.

import redirectMap from "./redirects-map.js"
import robotsTxt from "./robots.js"

export default {
  async fetch(request, env) {
    const url = new URL(request.url)
    const pathname = url.pathname
    const decodedPath = decodeURIComponent(pathname)
    // Obsidian Publish encoded spaces as `+` (form-encoding). decodeURIComponent
    // doesn't reverse that — only URLSearchParams does, and only for queries.
    const plusNormalized = decodedPath.replaceAll("+", " ")

    // robots.txt — served directly from the Worker so the AI/search policy
    // lives with the rest of the edge config (see src/robots.js).
    if (pathname === "/robots.txt") {
      return new Response(robotsTxt, {
        status: 200,
        headers: {
          "Content-Type": "text/plain; charset=utf-8",
          "Cache-Control": "public, max-age=86400",
        },
      })
    }

    // Exact-match redirects (try percent-encoded, decoded, and plus-as-space forms)
    let target =
      redirectMap[pathname] ??
      redirectMap[decodedPath] ??
      redirectMap[plusNormalized]

    // Catch-all: the Papers folder was removed in favour of inline blog
    // links. Route any legacy /Papers/* URL to the blog's paper review tag.
    if (!target) {
      if (pathname.startsWith("/Papers/") || decodedPath.startsWith("/Papers/")) {
        target = "https://andlukyane.com/tag/paperreview"
      }
    }

    if (target) {
      const absoluteTarget = target.startsWith("http")
        ? target
        : new URL(target, url.origin).toString()
      return Response.redirect(absoluteTarget, 301)
    }

    // Fall through to the static Quartz build
    return env.ASSETS.fetch(request)
  },
}
