// dswok-quartz edge Worker
//
// Handles legacy Obsidian Publish URL redirects (e.g.
// /General%20ML/Decision%20Tree  ->  /General-ML/Decision-Tree),
// then falls through to the static Quartz output via the ASSETS binding.
//
// The redirect map is generated by ../generate-redirects.mjs at build time.

import redirectMap from "./redirects-map.js"

export default {
  async fetch(request, env) {
    const url = new URL(request.url)
    const pathname = url.pathname
    const decodedPath = decodeURIComponent(pathname)

    // Exact-match redirects (try both percent-encoded and decoded forms)
    let target = redirectMap[pathname] ?? redirectMap[decodedPath]

    // Catch-all: the Papers folder was removed in favour of inline blog
    // links. Route any legacy /Papers/* URL to the blog's paper review tag.
    if (!target) {
      if (pathname.startsWith("/Papers/") || decodedPath.startsWith("/Papers/")) {
        target = "https://andlukyane.com/tag/paperreview"
      }
    }

    if (target) {
      const absoluteTarget = target.startsWith("http")
        ? target
        : new URL(target, url.origin).toString()
      return Response.redirect(absoluteTarget, 301)
    }

    // Fall through to the static Quartz build
    return env.ASSETS.fetch(request)
  },
}
